spring:
  datasource:
    url: jdbc:postgresql://postgres-reservation:5432/reservation_db
    username: reservation_user
    password: reservation_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
    parameters:
      liquibase.secureParsing: false

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto

server:
  port: 8081

product-service:
  url: http://product-service:8082

logging:
  level:
    com.example: DEBUG

rabbitmq:
  queue:
    order: order.queue
    response: order.response.queue
  exchange: order.exchange
  routing:
    order: order.created
    response: order.response